config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  get "/profile", to: 'user#show'

  resources :products, only: %i[new show create destroy]

  post "/buy/:id", to: 'products#buy', as: 'product_buy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_many :line_items

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def sign_in_by_token
  #   sign_in(User.find_by(token: cookies[:token])) if cookies[:token] 
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.order(created_at: :desc)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def show
    @product = Product.find_by(id: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(permited_params.merge(buyer_id: nil))
    if @product.save
      redirect_to profile_path
      flash[:notice] = t('success')
    else
      redirect_to root_path
      flash[:notice] = t('failure')
    end
  end

  def destroy
    @product = current_user.products.find_by(id: params[:id])
    if @product.destroy
      redirect_to profile_path
      flash[:notice] = t('success')
    else
      redirect_to root_path
      flash[:notice] = t('failure')
    end
  end

  def buy
    @product = Product.find_by(id: params[:id])
    
    unless @product.buyer_id.nil?
      redirect_to root_path
      flash[:notice] = t('already_bought')
      return
    end

    if @product.update(buyer_id: current_user.id)
      redirect_to profile_path
      flash[:notice] = t('success')
    else
      redirect_to root_path
      flash[:notice] = t('failure')
    end
  end

  protected

  def permited_params
    params.require(:product).permit(:title, :description, :cost, :image)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    @user = current_user
    @products_sell = current_user.products
    @products_bought = Product.all.where(buyer_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/_post.html.slim
.col.card.shadow
  = image_tag product.image
  h2
    = link_to product.title, product_path(product), class: "text-decoration-none"
  p
    | #{t('product_description', description: product.description)}
  p
    | #{t('product_price', price: product.cost)}
  - unless product.buyer_id.nil?
    p.btn.btn-danger
      | #{t('sold_to', buyer: User.find_by(id: product.buyer_id).email)}

app/views/home/index.html.slim
.card.m-5.p-5.shadow
  h2
    | #{t('products')}
  .row.row-cols-1.row-cols-sm-2.row-cols-md-3.g-3
    - for product in @products
      = render 'home/post', product: product

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | #{t('hand_made_products_shop')}
    meta[name='viewport' content='width=device-width, initial-scale=1.0']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      = render 'shared/header'
    main[style='margin-top: 56px;']
      - if notice || alert
        .d-flex.align-items-center.justify-content-center
          .card.border-dark.shadow.p-1.w-50.m-3.text-center
            - unless notice.nil?
              p.notice
                | #{notice}
            - unless alert.nil?
              p.alert
                | #{alert}
      = yield

app/views/products/_form.html.slim
= simple_form_for(product) do |f|
  .form-group
    = f.label t('title')
    = f.input :title, autofocus: true, placeholder: t('title_placeholder'), required: true, label: false, input_html: { class: 'form-control' }
  .form-group
    = f.label t('description')
    = f.input :description, as: :text, placeholder: t('description_placeholder'), required: true, label: false, input_html: { class: 'form-control' }
  .form-group
    = f.label t('cost')
    = f.number_field :cost, min: 0, step: 0.01, placeholder: t('cost_placeholder'), required: true, label: false, input_html: { class: 'form-control-number' }
  .form-group
    = f.label t('image')
    = f.file_field :image, label: false, input_html: { class: 'form-control' , data: { tubro: false } }
  .form-group.d-flex.align-items-center.justify-content-center.m-2
    = f.submit t('confirm'), class: 'btn btn-primary'

app/views/products/new.html.slim
.d-flex.align-items-center.justify-content-center
  .card.border-dark.shadow.p-3.w-25.m-5
    h4.card-title.mb-4.mt-1.d-flex.align-items-center.justify-content-center.m-2
      | #{t('new_product')}
    = render 'products/form', product: @product

app/views/products/show.html.slim
.d-flex.align-items-center.justify-content-center
  .card.border-dark.shadow.p-3.w-50
    = image_tag @product.image
    h2
      | #{t('product_title', title: @product.title)}
    p
      | #{t('product_description', description: @product.description)}
    p
      | #{t('product_price', price: @product.cost)}
    - unless @product.buyer_id.nil?
      p.btn.btn-danger
        | #{t('sold_to', buyer: User.find_by(id: @product.buyer_id).email)}
    - else
      = button_to t('buy'), product_buy_path(@product.id), { class: 'text-decoration-none btn btn-primary' }

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .container-fluid
    .collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-md-0
        li.nav-item
          = link_to t('main_page'), root_path, class: 'nav-link text-decoration-none'
        - if user_signed_in?
          li.nav-item
            = link_to current_user['email'], profile_path, class: 'nav-link text-decoration-none'
          li.nav-item
            = link_to t('create_product'), new_product_path, class: 'nav-link text-decoration-none'
          li.nav-item
            = button_to t('sign_out'), destroy_user_session_path, { method: :delete, class: 'nav-link text-decoration-none border-0 bg-dark btn-link' }
        - else
          li.nav-item
            = link_to t('sign_in'), new_user_session_path, class: 'nav-link text-decoration-none'
          li.nav-item
            = link_to t('sign_up'), new_user_registration_path, class: 'nav-link text-decoration-none'

app/views/user/show.html.slim
h1
  | Продаешь
table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } = t('title')
      th{ scope: :col } = t('description')
      th{ scope: :col } = t('cost')
      th
  tbody
    - @products_sell.each do |product|
      tr
        td = product.title
        td = product.description
        td = product.cost
        td.d-flex.flex-row-reverse
          = link_to t('show'), product_path(product), class: 'text-decoration-none btn btn-primary'
h1
  | Купил
table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } = t('title')
      th{ scope: :col } = t('description')
      th{ scope: :col } = t('cost')
      th
  tbody
    - @products_bought.each do |product|
      tr
        td = product.title
        td = product.description
        td = product.cost
        td.d-flex.flex-row-reverse
          = link_to t('show'), product_path(product), class: 'text-decoration-none btn btn-primary'